stages:
  - build
  - post-merge


variables:                         &global-vars
  FF_GITLAB_REGISTRY_HELPER_IMAGE:   'true'

build-simnetscripts-image-and-push-temporarly-in-paritypr:
  variables:
    <<:                            *global-vars
  image:                           quay.io/podman/stable
  tags:
    - parity-simnetscripts-build
  variables:
    # random name to replace simnetscripts until we will have private docker repo 
    CONTAINER_IMAGE:               paritypr/simnetscripts
  stage:                           build
  before_script:
    - test "$DOCKER_SIMNET_USER" -a "$DOCKER_SIMNET_PASS" ||
        ( echo "No docker credentials provided"; exit 1 )
  script:
    - |
      echo "LOG INFO step 4 build container image $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA"
      echo "$DOCKER_SIMNET_PASS" \
           | podman login --username "$DOCKER_SIMNET_USER" --password-stdin docker.io
      whoami
      podman info
      df -h | grep /var/lib/containers
      time podman run \
        --volume .:/build  \
        --volume /var/lib/containers/:/var/lib/containers \
        --device /dev/fuse \
        --privileged   \
        quay.io/buildah/stable \
            buildah bud  \
              --layers=true  \
              --cache-from  "$CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA" \
              --tag         "$CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA" \
              /build 
      echo "LOG INFO step 5 image $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA built successfully"
      echo "$DOCKER_SIMNET_PASS" \
           | podman  login --username "$DOCKER_SIMNET_USER" --password-stdin docker.io

      podman push --format=v2s2 "$CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA"
      echo "LOG INFO step 6 image $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA pushed successfully"

      echo "LOG check if need to cleanup dangling images"
      df -h | grep /var/lib/containers
      CACHE_USE_PERCENT="$(df -h | grep -vE '/var/lib/containers/.*' | grep /var/lib/containers | awk '{print $5}' | sed 's/%//g')"
      test -n "$CACHE_USE_PERCENT" \
              || ( echo "This variable can't be emtpy" ; exit 1 )

      if test "$CACHE_USE_PERCENT" -ge 80 ; then 
        echo "LOG INFO need to cleanup cache, value: $CACHE_USE_PERCENT"
        time podman rmi -f $(podman images -q -f "dangling=true")
      else 
        echo "LOG INFO No Cleanup needed this time value: $CACHE_USE_PERCENT"
      fi
  retry: 1
  after_script:
    - podman logout docker.io


  # TODO: How to test that image is good
      # test-simnetscripts-image:
      #   variables:
      #     <<:                            *global-vars
      #   variables:
      #     CONTAINER_IMAGE:               paritypr/simnetscripts
      #   image:                           "${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      #   interruptible:                   true
      #   stage:                           post-build
      #   tags:
      #     - parity-simnetscripts
      #   needs:
      #     - job:                         build-simnetscripts-image-and-push-temporarly-in-paritypr
      #   script:
      #     - echo "LOG INFO step 6 test image ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA} "
      #     - /home/nonroot/gurke/scripts/run-test-environment-manager.sh -t run-external-tool-test.sh
      #   retry: 2

push-simnetscripts-image-to-paritytech:
  variables:
    <<:                            *global-vars
    UPSTREAM_BUILD_TRIGGER:        $BUILD_SUBFLOOD
  stage:                           post-merge
  needs:
    - job:                         test-simnetscripts-image
  image:                           quay.io/buildah/stable
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$UPSTREAM_BUILD_TRIGGER == "true"'
  tags:
    - parity-simnetscripts-build
  before_script:
    - test "$Docker_Hub_User_Parity" -a "$Docker_Hub_Pass_Parity" ||
        ( echo "no docker credentials provided"; exit 1 )
  script:
    - echo "LOG INFO step 7 update paritytech/simnetscripts:latest"
    - echo "$Docker_Hub_Pass_Parity" |
        buildah login --username "$Docker_Hub_User_Parity" --password-stdin docker.io
    - buildah info
    - 'buildah pull "paritypr/simnetscripts:$CI_COMMIT_SHORT_SHA"'
    - 'buildah tag "paritypr/simnetscripts:$CI_COMMIT_SHORT_SHA" paritytech/simnetscripts:latest'
    - 'buildah push --format=v2s2 paritytech/simnetscripts:latest'
  after_script:
    - buildah logout docker.io
