stages:
    - build-test

trigger-simnet-for-build-and-test:
  stage:                     build-test
  variables: 
    TRGR_PROJECT:            "${CI_PROJECT_NAME}"
    # The branch or tag name for which project is built. 
    TRGR_REF:                "${CI_COMMIT_REF_NAME}"
  trigger:
    project: simnet 
    branch: master




      # trigger-simnet-for-build-and-test:
      #   stage:                     build-test
      #   variables: 
      #     # The branch or tag name for which project is built. 
      #     TRGR_REF:                "${CI_COMMIT_REF_NAME}"
      #   image:                     "docker.io/paritytech/tools:latest"
      #   script:
      #     - echo 'TRGR_REF is ${TRGR_REF}'
      #     - ./scripts/trigger_pipeline.sh
      #         --simnet-version=master
      #         --upstream-project="${CI_PROJECT_NAME}"
      #         --upstream-ref="${CI_COMMIT_REF_NAME}"
      #         --downstream-id=332
      #         --image-name=""
      #         --image-tag=""
      #   tags:
      #     - parity-simnetscripts
